DELTA_TIME = 50
N_ROWS = 2
N_COLS = 3
WINDOW_WIDTH = 600
WINDOW_HEIGHT = 600
SPAWN_SIDE_LEN = 160
SPAWN_PADDING_WIDTH = (WINDOW_WIDTH - N_COLS * SPAWN_SIDE_LEN) / (N_COLS + 1)
SPAWN_PADDING_HEIGHT = (WINDOW_HEIGHT - N_ROWS * SPAWN_SIDE_LEN) / (N_ROWS + 1)

MAX_N_DIGITS = 4

FONT_PATH = "res/VCR_OSD_MONO_1.001.ttf"
FONT_SIZE = 32
PADDING_UI_TOP = 30
LARGE_FONT_SIZE = 50
PADDING_LARGE_UI_TOP = 36

SPAWN_INTERVAL = 2000